apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: swn23271z-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:5af8c9a48d097bc0f70ed627bf7b496eaa3e1575@sha256:10a456acc9eea86f9ec9a5e317ace8b08d8d28c4f149c0e0e9f71aa1bdb957eb
          name: container-image
